services:
  - type: web
    name: devs-clinic-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_MS
        value: "86400000"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://clinic-app-nine-smoky.vercel.app"
